--------------------------------------------------------
--  Fichier créé - jeudi-février-27-2025   
--------------------------------------------------------
DROP TABLE "ABDALLAH"."ARCHITECTE";
DROP TABLE "ABDALLAH"."FORMATION";
DROP TABLE "ABDALLAH"."CLIENT";
DROP TABLE "ABDALLAH"."PROJET";
DROP TABLE "ABDALLAH"."TACHE";
--------------------------------------------------------
--  DDL for Sequence ARCHITECTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ABDALLAH"."ARCHITECTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FORMATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ABDALLAH"."FORMATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CLIENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ABDALLAH"."CLIENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PROJET_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ABDALLAH"."PROJET_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TACHE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ABDALLAH"."TACHE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ARCHITECTE
--------------------------------------------------------

  CREATE TABLE "ABDALLAH"."ARCHITECTE" 
   (	"ID_ARCHITECTE" NUMBER(10,0), 
	"NOM" VARCHAR2(100 BYTE), 
	"COURRIEL" VARCHAR2(100 BYTE), 
	"ROLE" VARCHAR2(20 BYTE), 
	"MOT_DE_PASSE" VARCHAR2(255 BYTE), 
	"SECURITY_QUESTION" VARCHAR2(255 BYTE), 
	"SECURITY_ANSWER" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FORMATION
--------------------------------------------------------

  CREATE TABLE "ABDALLAH"."FORMATION" 
   (	"ID_FORMATION" NUMBER(10,0), 
	"DATEDEBUT" DATE, 
	"DATEFIN" DATE, 
	"FORMATEUR" VARCHAR2(100 BYTE), 
	"LIEU" VARCHAR2(255 BYTE), 
	"PRIX" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "ABDALLAH"."CLIENT" 
   (	"ID_CLIENT" NUMBER(10,0), 
	"NOM" VARCHAR2(100 BYTE), 
	"PRENOM" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"NUM_TLF" VARCHAR2(20 BYTE), 
	"NB_PROJET" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROJET
--------------------------------------------------------

  CREATE TABLE "ABDALLAH"."PROJET" 
   (	"ID_PROJET" NUMBER(10,0), 
	"NOM_PROJET" VARCHAR2(255 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"STATUT" VARCHAR2(20 BYTE), 
	"DESCRIPTION" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TACHE
--------------------------------------------------------

  CREATE TABLE "ABDALLAH"."TACHE" 
   (	"ID_TACHE" NUMBER(10,0), 
	"DATEDEB" DATE, 
	"DATEFIN" DATE, 
	"MISSION" VARCHAR2(255 BYTE), 
	"STATUT" VARCHAR2(20 BYTE), 
	"DESCRIPTION" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into ABDALLAH.ARCHITECTE
SET DEFINE OFF;
REM INSERTING into ABDALLAH.FORMATION
SET DEFINE OFF;
REM INSERTING into ABDALLAH.CLIENT
SET DEFINE OFF;
REM INSERTING into ABDALLAH.PROJET
SET DEFINE OFF;
REM INSERTING into ABDALLAH.TACHE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007022
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDALLAH"."SYS_C007022" ON "ABDALLAH"."ARCHITECTE" ("ID_ARCHITECTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007023
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDALLAH"."SYS_C007023" ON "ABDALLAH"."ARCHITECTE" ("COURRIEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007010
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDALLAH"."SYS_C007010" ON "ABDALLAH"."FORMATION" ("ID_FORMATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007029
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDALLAH"."SYS_C007029" ON "ABDALLAH"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007030
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDALLAH"."SYS_C007030" ON "ABDALLAH"."CLIENT" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007015
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDALLAH"."SYS_C007015" ON "ABDALLAH"."PROJET" ("ID_PROJET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007035
--------------------------------------------------------

  CREATE UNIQUE INDEX "ABDALLAH"."SYS_C007035" ON "ABDALLAH"."TACHE" ("ID_TACHE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ARCHITECTE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABDALLAH"."ARCHITECTE_TRIGGER" 
BEFORE INSERT ON Architecte 
FOR EACH ROW 
BEGIN 
    SELECT architecte_seq.NEXTVAL INTO :NEW.Id_architecte FROM DUAL;
END;

/
ALTER TRIGGER "ABDALLAH"."ARCHITECTE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FORMATION_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABDALLAH"."FORMATION_TRIGGER" 
BEFORE INSERT ON Formation 
FOR EACH ROW 
BEGIN 
    SELECT formation_seq.NEXTVAL INTO :NEW.Id_formation FROM DUAL;
END;

/
ALTER TRIGGER "ABDALLAH"."FORMATION_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABDALLAH"."CLIENT_TRIGGER" 
BEFORE INSERT ON Client 
FOR EACH ROW 
BEGIN 
    SELECT client_seq.NEXTVAL INTO :NEW.Id_client FROM DUAL;
END;

/
ALTER TRIGGER "ABDALLAH"."CLIENT_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROJET_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABDALLAH"."PROJET_TRIGGER" 
BEFORE INSERT ON Projet 
FOR EACH ROW 
BEGIN 
    SELECT projet_seq.NEXTVAL INTO :NEW.Id_projet FROM DUAL;
END;

/
ALTER TRIGGER "ABDALLAH"."PROJET_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TACHE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ABDALLAH"."TACHE_TRIGGER" 
BEFORE INSERT ON Tache 
FOR EACH ROW 
BEGIN 
    SELECT tache_seq.NEXTVAL INTO :NEW.Id_tache FROM DUAL;
END;

/
ALTER TRIGGER "ABDALLAH"."TACHE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Synonymn DUAL
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DUAL" FOR "SYS"."DUAL";
--------------------------------------------------------
--  Constraints for Table ARCHITECTE
--------------------------------------------------------

  ALTER TABLE "ABDALLAH"."ARCHITECTE" ADD UNIQUE ("COURRIEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDALLAH"."ARCHITECTE" ADD PRIMARY KEY ("ID_ARCHITECTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDALLAH"."ARCHITECTE" MODIFY ("SECURITY_ANSWER" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."ARCHITECTE" MODIFY ("SECURITY_QUESTION" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."ARCHITECTE" MODIFY ("MOT_DE_PASSE" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."ARCHITECTE" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."ARCHITECTE" MODIFY ("COURRIEL" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."ARCHITECTE" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FORMATION
--------------------------------------------------------

  ALTER TABLE "ABDALLAH"."FORMATION" ADD PRIMARY KEY ("ID_FORMATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDALLAH"."FORMATION" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."FORMATION" MODIFY ("LIEU" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."FORMATION" MODIFY ("FORMATEUR" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."FORMATION" MODIFY ("DATEFIN" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."FORMATION" MODIFY ("DATEDEBUT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "ABDALLAH"."CLIENT" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDALLAH"."CLIENT" ADD PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDALLAH"."CLIENT" MODIFY ("NB_PROJET" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."CLIENT" MODIFY ("NUM_TLF" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."CLIENT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."CLIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJET
--------------------------------------------------------

  ALTER TABLE "ABDALLAH"."PROJET" ADD PRIMARY KEY ("ID_PROJET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDALLAH"."PROJET" MODIFY ("STATUT" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."PROJET" MODIFY ("DATE_FIN" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."PROJET" MODIFY ("DATE_DEBUT" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."PROJET" MODIFY ("NOM_PROJET" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TACHE
--------------------------------------------------------

  ALTER TABLE "ABDALLAH"."TACHE" ADD PRIMARY KEY ("ID_TACHE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ABDALLAH"."TACHE" MODIFY ("STATUT" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."TACHE" MODIFY ("MISSION" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."TACHE" MODIFY ("DATEFIN" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."TACHE" MODIFY ("DATEDEB" NOT NULL ENABLE);
