--------------------------------------------------------
--  Fichier créé - mercredi-février-26-2025   
--------------------------------------------------------
DROP TABLE "ABDALLAH"."FORMATIONS";
--------------------------------------------------------
--  DDL for Table FORMATIONS
--------------------------------------------------------

  CREATE TABLE "ABDALLAH"."FORMATIONS" 
   (	"ID" NUMBER, 
	"DATEDEBUT" DATE, 
	"DATEFIN" DATE, 
	"FORMATEUR" VARCHAR2(50 BYTE), 
	"LIEU" VARCHAR2(50 BYTE), 
	"PRIX" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ABDALLAH.FORMATIONS
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table FORMATIONS
--------------------------------------------------------

  ALTER TABLE "ABDALLAH"."FORMATIONS" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."FORMATIONS" MODIFY ("LIEU" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."FORMATIONS" MODIFY ("FORMATEUR" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."FORMATIONS" MODIFY ("DATEFIN" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."FORMATIONS" MODIFY ("DATEDEBUT" NOT NULL ENABLE);
  ALTER TABLE "ABDALLAH"."FORMATIONS" MODIFY ("ID" NOT NULL ENABLE);
